// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package networkdb is a generated protocol buffer package.

It is generated from these files:
	messages.proto
	rpcif.proto

It has these top-level messages:
	Result
	Configuration
	JoinClusterReq
	GroupID
	TableID
	EntryIn
	Entry
	EntryList
	PeerList
	Peer
	TableEvent
*/
package networkdb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperationResult int32

const (
	OperationResult_SUCCESS OperationResult = 0
	OperationResult_FAIL    OperationResult = 1
)

var OperationResult_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}
var OperationResult_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x OperationResult) String() string {
	return proto.EnumName(OperationResult_name, int32(x))
}
func (OperationResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TableOperation int32

const (
	TableOperation_CREATE TableOperation = 0
	TableOperation_UPDATE TableOperation = 1
	TableOperation_DELETE TableOperation = 2
)

var TableOperation_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}
var TableOperation_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x TableOperation) String() string {
	return proto.EnumName(TableOperation_name, int32(x))
}
func (TableOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Result struct {
	Status OperationResult `protobuf:"varint,1,opt,name=status,enum=networkdb.OperationResult" json:"status,omitempty"`
	Error  string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Data   []byte          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetStatus() OperationResult {
	if m != nil {
		return m.Status
	}
	return OperationResult_SUCCESS
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Result) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Configuration struct {
	// nodeName is the cluster wide unique name for this node.
	NodeName string `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	// bindAddr is the IP on which networkdb listens.
	BindAddr string `protobuf:"bytes,2,opt,name=bindAddr" json:"bindAddr,omitempty"`
	// bindPort is the local node's port to which we bind to for cluster communication.
	BindPort int32 `protobuf:"varint,3,opt,name=bindPort" json:"bindPort,omitempty"`
	// keys to be added to the Keyring of the memberlist. Key at index
	// 0 is the primary key
	Keys [][]byte `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Configuration) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Configuration) GetBindAddr() string {
	if m != nil {
		return m.BindAddr
	}
	return ""
}

func (m *Configuration) GetBindPort() int32 {
	if m != nil {
		return m.BindPort
	}
	return 0
}

func (m *Configuration) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type JoinClusterReq struct {
	Members []string `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *JoinClusterReq) Reset()                    { *m = JoinClusterReq{} }
func (m *JoinClusterReq) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterReq) ProtoMessage()               {}
func (*JoinClusterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinClusterReq) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupID struct {
	GroupName string `protobuf:"bytes,1,opt,name=groupName" json:"groupName,omitempty"`
}

func (m *GroupID) Reset()                    { *m = GroupID{} }
func (m *GroupID) String() string            { return proto.CompactTextString(m) }
func (*GroupID) ProtoMessage()               {}
func (*GroupID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GroupID) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type TableID struct {
	Group     *GroupID `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	TableName string   `protobuf:"bytes,2,opt,name=tableName" json:"tableName,omitempty"`
}

func (m *TableID) Reset()                    { *m = TableID{} }
func (m *TableID) String() string            { return proto.CompactTextString(m) }
func (*TableID) ProtoMessage()               {}
func (*TableID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TableID) GetGroup() *GroupID {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *TableID) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type EntryIn struct {
	Table *TableID `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Entry *Entry   `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *EntryIn) Reset()                    { *m = EntryIn{} }
func (m *EntryIn) String() string            { return proto.CompactTextString(m) }
func (*EntryIn) ProtoMessage()               {}
func (*EntryIn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EntryIn) GetTable() *TableID {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *EntryIn) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type Entry struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type EntryList struct {
	Table *TableID `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	List  []*Entry `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *EntryList) Reset()                    { *m = EntryList{} }
func (m *EntryList) String() string            { return proto.CompactTextString(m) }
func (*EntryList) ProtoMessage()               {}
func (*EntryList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *EntryList) GetTable() *TableID {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *EntryList) GetList() []*Entry {
	if m != nil {
		return m.List
	}
	return nil
}

type PeerList struct {
	Peers []*Peer `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *PeerList) Reset()                    { *m = PeerList{} }
func (m *PeerList) String() string            { return proto.CompactTextString(m) }
func (*PeerList) ProtoMessage()               {}
func (*PeerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PeerList) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Peer struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type TableEvent struct {
	Operation TableOperation `protobuf:"varint,1,opt,name=operation,enum=networkdb.TableOperation" json:"operation,omitempty"`
	Table     *TableID       `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Entry     *Entry         `protobuf:"bytes,3,opt,name=entry" json:"entry,omitempty"`
}

func (m *TableEvent) Reset()                    { *m = TableEvent{} }
func (m *TableEvent) String() string            { return proto.CompactTextString(m) }
func (*TableEvent) ProtoMessage()               {}
func (*TableEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TableEvent) GetOperation() TableOperation {
	if m != nil {
		return m.Operation
	}
	return TableOperation_CREATE
}

func (m *TableEvent) GetTable() *TableID {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *TableEvent) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "networkdb.Result")
	proto.RegisterType((*Configuration)(nil), "networkdb.Configuration")
	proto.RegisterType((*JoinClusterReq)(nil), "networkdb.JoinClusterReq")
	proto.RegisterType((*GroupID)(nil), "networkdb.GroupID")
	proto.RegisterType((*TableID)(nil), "networkdb.TableID")
	proto.RegisterType((*EntryIn)(nil), "networkdb.EntryIn")
	proto.RegisterType((*Entry)(nil), "networkdb.Entry")
	proto.RegisterType((*EntryList)(nil), "networkdb.EntryList")
	proto.RegisterType((*PeerList)(nil), "networkdb.PeerList")
	proto.RegisterType((*Peer)(nil), "networkdb.Peer")
	proto.RegisterType((*TableEvent)(nil), "networkdb.TableEvent")
	proto.RegisterEnum("networkdb.OperationResult", OperationResult_name, OperationResult_value)
	proto.RegisterEnum("networkdb.TableOperation", TableOperation_name, TableOperation_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x8d, 0x6d, 0x0c, 0x78, 0x48, 0x89, 0xb5, 0xea, 0xc1, 0x8d, 0x7a, 0x40, 0xab, 0x7e, 0x58,
	0x1c, 0xa8, 0x4a, 0x2b, 0xf5, 0x8c, 0xc0, 0xad, 0xa8, 0x50, 0x4b, 0x17, 0x72, 0xca, 0xc9, 0xc8,
	0x13, 0x64, 0x01, 0x5e, 0x77, 0xbd, 0x4e, 0xc4, 0x2f, 0xe9, 0xdf, 0xad, 0x76, 0xd7, 0xc6, 0x34,
	0x8a, 0xaa, 0xf6, 0xf6, 0xde, 0xcc, 0x9b, 0x37, 0x33, 0x9e, 0x35, 0xf4, 0x0f, 0x58, 0x14, 0xf1,
	0x16, 0x8b, 0x51, 0x2e, 0xb8, 0xe4, 0xc4, 0xcb, 0x50, 0x3e, 0x70, 0xb1, 0x4b, 0x36, 0xf4, 0x0e,
	0xda, 0x0c, 0x8b, 0x72, 0x2f, 0xc9, 0x18, 0xda, 0x85, 0x8c, 0x65, 0x59, 0x04, 0xd6, 0xc0, 0x0a,
	0xfb, 0xe3, 0xeb, 0xd1, 0x49, 0x35, 0xfa, 0x9e, 0xa3, 0x88, 0x65, 0xca, 0x33, 0xa3, 0x65, 0x95,
	0x92, 0x3c, 0x07, 0x17, 0x85, 0xe0, 0x22, 0xb0, 0x07, 0x56, 0xe8, 0x31, 0x43, 0x08, 0x81, 0x56,
	0x12, 0xcb, 0x38, 0x70, 0x06, 0x56, 0x78, 0xc9, 0x34, 0xa6, 0x0f, 0xf0, 0x6c, 0xca, 0xb3, 0xbb,
	0x74, 0x5b, 0x1a, 0x23, 0x72, 0x0d, 0xdd, 0x8c, 0x27, 0xf8, 0x2d, 0x3e, 0xa0, 0x6e, 0xe8, 0xb1,
	0x13, 0x57, 0xb9, 0x4d, 0x9a, 0x25, 0x93, 0x24, 0xa9, 0x9d, 0x4f, 0xbc, 0xce, 0x2d, 0xb9, 0x90,
	0xba, 0x81, 0xcb, 0x4e, 0x5c, 0x35, 0xde, 0xe1, 0xb1, 0x08, 0x5a, 0x03, 0x47, 0x35, 0x56, 0x98,
	0x0e, 0xa1, 0xff, 0x95, 0xa7, 0xd9, 0x74, 0x5f, 0x16, 0x12, 0x05, 0xc3, 0x9f, 0x24, 0x80, 0xce,
	0x01, 0x0f, 0x1b, 0x14, 0x6a, 0x53, 0x27, 0xf4, 0x58, 0x4d, 0xe9, 0x5b, 0xe8, 0x7c, 0x11, 0xbc,
	0xcc, 0xe7, 0x33, 0xf2, 0x12, 0xbc, 0xad, 0x82, 0x67, 0xf3, 0x35, 0x01, 0xfa, 0x03, 0x3a, 0xeb,
	0x78, 0xb3, 0xc7, 0xf9, 0x8c, 0x84, 0xe0, 0xea, 0xb8, 0x16, 0xf5, 0xc6, 0xe4, 0xec, 0xab, 0x55,
	0x5e, 0xcc, 0x08, 0x94, 0xa5, 0x54, 0x45, 0xda, 0xd2, 0xac, 0xd5, 0x04, 0xe8, 0x2d, 0x74, 0xa2,
	0x4c, 0x8a, 0xe3, 0x3c, 0x53, 0x96, 0x3a, 0xfe, 0x84, 0x65, 0xd5, 0x95, 0x19, 0x01, 0x79, 0x03,
	0x2e, 0xaa, 0x22, 0x6d, 0xd7, 0x1b, 0xfb, 0x67, 0x4a, 0x6d, 0xc6, 0x4c, 0x9a, 0xbe, 0x03, 0x57,
	0x73, 0xe2, 0x83, 0xb3, 0xc3, 0x63, 0xb5, 0x90, 0x82, 0xea, 0x84, 0xf7, 0xf1, 0xbe, 0x34, 0x13,
	0x5d, 0x32, 0x43, 0xe8, 0x2d, 0x78, 0xba, 0x60, 0x91, 0x16, 0xf2, 0x3f, 0xe6, 0x79, 0x05, 0xad,
	0x7d, 0x5a, 0xc8, 0xc0, 0x1e, 0x38, 0x4f, 0x8e, 0xa3, 0xb3, 0xf4, 0x3d, 0x74, 0x97, 0x88, 0x42,
	0x7b, 0xbf, 0x06, 0x37, 0xc7, 0xfa, 0x14, 0xbd, 0xf1, 0xd5, 0x59, 0x89, 0xd2, 0x30, 0x93, 0xa5,
	0x43, 0x68, 0x29, 0xaa, 0x2e, 0x9c, 0x35, 0x17, 0xd1, 0x98, 0xf4, 0xc1, 0x4e, 0xf3, 0xea, 0x83,
	0xda, 0x69, 0x4e, 0x7f, 0x59, 0x00, 0x7a, 0xae, 0xe8, 0x1e, 0x33, 0x49, 0x3e, 0x81, 0xc7, 0xeb,
	0xe7, 0x5b, 0x3d, 0xed, 0x17, 0x8f, 0x37, 0x68, 0xde, 0x77, 0xa3, 0x6d, 0xd6, 0xb6, 0xff, 0xf9,
	0x0c, 0xce, 0x5f, 0xcf, 0x30, 0x0c, 0xe1, 0xea, 0xd1, 0x9f, 0x44, 0x7a, 0xd0, 0x59, 0xdd, 0x4c,
	0xa7, 0xd1, 0x6a, 0xe5, 0x5f, 0x90, 0x2e, 0xb4, 0x3e, 0x4f, 0xe6, 0x0b, 0xdf, 0x1a, 0x7e, 0x84,
	0xfe, 0x9f, 0x83, 0x11, 0x80, 0xf6, 0x94, 0x45, 0x93, 0x75, 0xe4, 0x5f, 0x28, 0x7c, 0xb3, 0x9c,
	0x29, 0x6c, 0x29, 0x3c, 0x8b, 0x16, 0xd1, 0x3a, 0xf2, 0xed, 0x4d, 0x5b, 0xff, 0xde, 0x1f, 0x7e,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x73, 0x7b, 0x97, 0x0f, 0xf0, 0x03, 0x00, 0x00,
}
