// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcif.proto

package networkdb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConfigurationManagement service

type ConfigurationManagementClient interface {
	// Component initialization
	Initialize(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*Result, error)
}

type configurationManagementClient struct {
	cc *grpc.ClientConn
}

func NewConfigurationManagementClient(cc *grpc.ClientConn) ConfigurationManagementClient {
	return &configurationManagementClient{cc}
}

func (c *configurationManagementClient) Initialize(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.ConfigurationManagement/Initialize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConfigurationManagement service

type ConfigurationManagementServer interface {
	// Component initialization
	Initialize(context.Context, *Configuration) (*Result, error)
}

func RegisterConfigurationManagementServer(s *grpc.Server, srv ConfigurationManagementServer) {
	s.RegisterService(&_ConfigurationManagement_serviceDesc, srv)
}

func _ConfigurationManagement_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Configuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationManagementServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.ConfigurationManagement/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationManagementServer).Initialize(ctx, req.(*Configuration))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigurationManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "networkdb.ConfigurationManagement",
	HandlerType: (*ConfigurationManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _ConfigurationManagement_Initialize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcif.proto",
}

// Client API for ClusterManagement service

type ClusterManagementClient interface {
	// // Cluster related operations
	// rpc StateCluster () returns (State) {}
	JoinCluster(ctx context.Context, in *JoinClusterReq, opts ...grpc.CallOption) (*Result, error)
	// rpc LeaveCluster () returns (Result) {}
	PeersCluster(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PeerList, error)
}

type clusterManagementClient struct {
	cc *grpc.ClientConn
}

func NewClusterManagementClient(cc *grpc.ClientConn) ClusterManagementClient {
	return &clusterManagementClient{cc}
}

func (c *clusterManagementClient) JoinCluster(ctx context.Context, in *JoinClusterReq, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.ClusterManagement/JoinCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) PeersCluster(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PeerList, error) {
	out := new(PeerList)
	err := grpc.Invoke(ctx, "/networkdb.ClusterManagement/PeersCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClusterManagement service

type ClusterManagementServer interface {
	// // Cluster related operations
	// rpc StateCluster () returns (State) {}
	JoinCluster(context.Context, *JoinClusterReq) (*Result, error)
	// rpc LeaveCluster () returns (Result) {}
	PeersCluster(context.Context, *google_protobuf.Empty) (*PeerList, error)
}

func RegisterClusterManagementServer(s *grpc.Server, srv ClusterManagementServer) {
	s.RegisterService(&_ClusterManagement_serviceDesc, srv)
}

func _ClusterManagement_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.ClusterManagement/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).JoinCluster(ctx, req.(*JoinClusterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_PeersCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).PeersCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.ClusterManagement/PeersCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).PeersCluster(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "networkdb.ClusterManagement",
	HandlerType: (*ClusterManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinCluster",
			Handler:    _ClusterManagement_JoinCluster_Handler,
		},
		{
			MethodName: "PeersCluster",
			Handler:    _ClusterManagement_PeersCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcif.proto",
}

// Client API for GroupManagement service

type GroupManagementClient interface {
	// // Group operations
	JoinGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error)
	LeaveGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error)
	// rpc ListGroup () return (Result) {}
	PeersGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*PeerList, error)
}

type groupManagementClient struct {
	cc *grpc.ClientConn
}

func NewGroupManagementClient(cc *grpc.ClientConn) GroupManagementClient {
	return &groupManagementClient{cc}
}

func (c *groupManagementClient) JoinGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.GroupManagement/JoinGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagementClient) LeaveGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.GroupManagement/LeaveGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagementClient) PeersGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*PeerList, error) {
	out := new(PeerList)
	err := grpc.Invoke(ctx, "/networkdb.GroupManagement/PeersGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GroupManagement service

type GroupManagementServer interface {
	// // Group operations
	JoinGroup(context.Context, *GroupID) (*Result, error)
	LeaveGroup(context.Context, *GroupID) (*Result, error)
	// rpc ListGroup () return (Result) {}
	PeersGroup(context.Context, *GroupID) (*PeerList, error)
}

func RegisterGroupManagementServer(s *grpc.Server, srv GroupManagementServer) {
	s.RegisterService(&_GroupManagement_serviceDesc, srv)
}

func _GroupManagement_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.GroupManagement/JoinGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).JoinGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManagement_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.GroupManagement/LeaveGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).LeaveGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManagement_PeersGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).PeersGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.GroupManagement/PeersGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).PeersGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "networkdb.GroupManagement",
	HandlerType: (*GroupManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinGroup",
			Handler:    _GroupManagement_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _GroupManagement_LeaveGroup_Handler,
		},
		{
			MethodName: "PeersGroup",
			Handler:    _GroupManagement_PeersGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcif.proto",
}

// Client API for EntryManagement service

type EntryManagementClient interface {
	// Entry operations
	CreateEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*Result, error)
	ReadEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*EntryIn, error)
	UpdateEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*Result, error)
	DeleteEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*Result, error)
	// Table operations
	ReadTable(ctx context.Context, in *TableID, opts ...grpc.CallOption) (*EntryList, error)
	WatchTable(ctx context.Context, in *TableID, opts ...grpc.CallOption) (EntryManagement_WatchTableClient, error)
}

type entryManagementClient struct {
	cc *grpc.ClientConn
}

func NewEntryManagementClient(cc *grpc.ClientConn) EntryManagementClient {
	return &entryManagementClient{cc}
}

func (c *entryManagementClient) CreateEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.EntryManagement/CreateEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) ReadEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*EntryIn, error) {
	out := new(EntryIn)
	err := grpc.Invoke(ctx, "/networkdb.EntryManagement/ReadEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) UpdateEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.EntryManagement/UpdateEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) DeleteEntryRpc(ctx context.Context, in *EntryIn, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.EntryManagement/DeleteEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) ReadTable(ctx context.Context, in *TableID, opts ...grpc.CallOption) (*EntryList, error) {
	out := new(EntryList)
	err := grpc.Invoke(ctx, "/networkdb.EntryManagement/ReadTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) WatchTable(ctx context.Context, in *TableID, opts ...grpc.CallOption) (EntryManagement_WatchTableClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EntryManagement_serviceDesc.Streams[0], c.cc, "/networkdb.EntryManagement/WatchTable", opts...)
	if err != nil {
		return nil, err
	}
	x := &entryManagementWatchTableClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EntryManagement_WatchTableClient interface {
	Recv() (*TableEvent, error)
	grpc.ClientStream
}

type entryManagementWatchTableClient struct {
	grpc.ClientStream
}

func (x *entryManagementWatchTableClient) Recv() (*TableEvent, error) {
	m := new(TableEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for EntryManagement service

type EntryManagementServer interface {
	// Entry operations
	CreateEntryRpc(context.Context, *EntryIn) (*Result, error)
	ReadEntryRpc(context.Context, *EntryIn) (*EntryIn, error)
	UpdateEntryRpc(context.Context, *EntryIn) (*Result, error)
	DeleteEntryRpc(context.Context, *EntryIn) (*Result, error)
	// Table operations
	ReadTable(context.Context, *TableID) (*EntryList, error)
	WatchTable(*TableID, EntryManagement_WatchTableServer) error
}

func RegisterEntryManagementServer(s *grpc.Server, srv EntryManagementServer) {
	s.RegisterService(&_EntryManagement_serviceDesc, srv)
}

func _EntryManagement_CreateEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).CreateEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.EntryManagement/CreateEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).CreateEntryRpc(ctx, req.(*EntryIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_ReadEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).ReadEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.EntryManagement/ReadEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).ReadEntryRpc(ctx, req.(*EntryIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_UpdateEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).UpdateEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.EntryManagement/UpdateEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).UpdateEntryRpc(ctx, req.(*EntryIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_DeleteEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).DeleteEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.EntryManagement/DeleteEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).DeleteEntryRpc(ctx, req.(*EntryIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_ReadTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).ReadTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.EntryManagement/ReadTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).ReadTable(ctx, req.(*TableID))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_WatchTable_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TableID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntryManagementServer).WatchTable(m, &entryManagementWatchTableServer{stream})
}

type EntryManagement_WatchTableServer interface {
	Send(*TableEvent) error
	grpc.ServerStream
}

type entryManagementWatchTableServer struct {
	grpc.ServerStream
}

func (x *entryManagementWatchTableServer) Send(m *TableEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _EntryManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "networkdb.EntryManagement",
	HandlerType: (*EntryManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntryRpc",
			Handler:    _EntryManagement_CreateEntryRpc_Handler,
		},
		{
			MethodName: "ReadEntryRpc",
			Handler:    _EntryManagement_ReadEntryRpc_Handler,
		},
		{
			MethodName: "UpdateEntryRpc",
			Handler:    _EntryManagement_UpdateEntryRpc_Handler,
		},
		{
			MethodName: "DeleteEntryRpc",
			Handler:    _EntryManagement_DeleteEntryRpc_Handler,
		},
		{
			MethodName: "ReadTable",
			Handler:    _EntryManagement_ReadTable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTable",
			Handler:       _EntryManagement_WatchTable_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpcif.proto",
}

// Client API for DiagnoseManagement service

type DiagnoseManagementClient interface {
	Ready(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Result, error)
	WatchTest(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (DiagnoseManagement_WatchTestClient, error)
}

type diagnoseManagementClient struct {
	cc *grpc.ClientConn
}

func NewDiagnoseManagementClient(cc *grpc.ClientConn) DiagnoseManagementClient {
	return &diagnoseManagementClient{cc}
}

func (c *diagnoseManagementClient) Ready(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/networkdb.DiagnoseManagement/Ready", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnoseManagementClient) WatchTest(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (DiagnoseManagement_WatchTestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DiagnoseManagement_serviceDesc.Streams[0], c.cc, "/networkdb.DiagnoseManagement/WatchTest", opts...)
	if err != nil {
		return nil, err
	}
	x := &diagnoseManagementWatchTestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiagnoseManagement_WatchTestClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type diagnoseManagementWatchTestClient struct {
	grpc.ClientStream
}

func (x *diagnoseManagementWatchTestClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DiagnoseManagement service

type DiagnoseManagementServer interface {
	Ready(context.Context, *google_protobuf.Empty) (*Result, error)
	WatchTest(*google_protobuf.Empty, DiagnoseManagement_WatchTestServer) error
}

func RegisterDiagnoseManagementServer(s *grpc.Server, srv DiagnoseManagementServer) {
	s.RegisterService(&_DiagnoseManagement_serviceDesc, srv)
}

func _DiagnoseManagement_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnoseManagementServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkdb.DiagnoseManagement/Ready",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnoseManagementServer).Ready(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagnoseManagement_WatchTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiagnoseManagementServer).WatchTest(m, &diagnoseManagementWatchTestServer{stream})
}

type DiagnoseManagement_WatchTestServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type diagnoseManagementWatchTestServer struct {
	grpc.ServerStream
}

func (x *diagnoseManagementWatchTestServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

var _DiagnoseManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "networkdb.DiagnoseManagement",
	HandlerType: (*DiagnoseManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ready",
			Handler:    _DiagnoseManagement_Ready_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTest",
			Handler:       _DiagnoseManagement_WatchTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpcif.proto",
}

func init() { proto.RegisterFile("rpcif.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdd, 0xce, 0xd2, 0x40,
	0x10, 0x86, 0xa9, 0x89, 0x26, 0x1d, 0x08, 0x84, 0xf5, 0xbf, 0x9e, 0x71, 0x01, 0x85, 0xa0, 0x06,
	0xd1, 0x70, 0x44, 0x89, 0xa9, 0xc1, 0xc4, 0x34, 0xfe, 0x1c, 0x6f, 0x61, 0xa8, 0x1b, 0xcb, 0x6e,
	0xdd, 0xdd, 0x62, 0xf0, 0x02, 0x3c, 0xf7, 0x6a, 0xbc, 0x2f, 0xaf, 0xc0, 0xec, 0x56, 0xbe, 0x6c,
	0x49, 0xfb, 0x25, 0x70, 0xc8, 0x3b, 0xfb, 0xcc, 0x3c, 0x43, 0x07, 0xba, 0xb2, 0xd8, 0xb0, 0x5d,
	0x58, 0x48, 0xa1, 0x05, 0xf1, 0x39, 0xea, 0x1f, 0x42, 0x7e, 0xdb, 0xa6, 0xc1, 0xb3, 0x4c, 0x88,
	0x2c, 0xc7, 0xb1, 0x2d, 0xa4, 0xe5, 0x6e, 0x8c, 0xfb, 0x42, 0x1f, 0xab, 0x77, 0x41, 0x7f, 0x8f,
	0x4a, 0xd1, 0x0c, 0x55, 0xf5, 0x7b, 0xfa, 0x19, 0x1e, 0x2f, 0x05, 0xdf, 0xb1, 0xac, 0x94, 0x54,
	0x33, 0xc1, 0xdf, 0x53, 0x4e, 0x33, 0xdc, 0x23, 0xd7, 0xe4, 0x0d, 0x40, 0xcc, 0x99, 0x66, 0x34,
	0x67, 0x3f, 0x91, 0x3c, 0x09, 0x6f, 0x26, 0x84, 0x35, 0x22, 0x18, 0x3a, 0x95, 0x04, 0x55, 0x99,
	0xeb, 0x51, 0x67, 0xfa, 0xdb, 0x83, 0xe1, 0x32, 0x2f, 0x95, 0x46, 0xe9, 0xb4, 0x5c, 0x40, 0xf7,
	0x9d, 0x60, 0xfc, 0x7f, 0x81, 0x3c, 0x75, 0x48, 0x27, 0x4f, 0xf0, 0x7b, 0x63, 0x53, 0xb2, 0x80,
	0xde, 0x07, 0x44, 0xa9, 0x4e, 0xfc, 0xa3, 0xb0, 0x5a, 0x35, 0x3c, 0xad, 0x1a, 0xae, 0xcc, 0xaa,
	0xc1, 0x7d, 0x07, 0x36, 0xc0, 0x9a, 0x29, 0xe3, 0xf4, 0xc7, 0x83, 0xc1, 0x5b, 0x29, 0xca, 0xc2,
	0x31, 0x7a, 0x01, 0xbe, 0x99, 0x6c, 0x63, 0x42, 0x1c, 0xce, 0x26, 0x71, 0xd4, 0x2c, 0xf2, 0x12,
	0x60, 0x8d, 0xf4, 0x80, 0x17, 0x62, 0x33, 0x00, 0xeb, 0xdf, 0x8e, 0xb5, 0x98, 0xff, 0xbd, 0x03,
	0x83, 0x15, 0xd7, 0xf2, 0xe8, 0x98, 0xcf, 0xa1, 0xbf, 0x94, 0x48, 0x35, 0xda, 0x42, 0x52, 0x6c,
	0x6a, 0x0d, 0x6d, 0x18, 0x37, 0x7f, 0x1c, 0xf2, 0x0a, 0x7a, 0x09, 0xd2, 0xed, 0xad, 0x60, 0x43,
	0x36, 0xea, 0x98, 0xa1, 0x9f, 0x8a, 0xed, 0x55, 0x43, 0xe7, 0xd0, 0x8f, 0x30, 0xc7, 0x6b, 0xd0,
	0x19, 0xf8, 0xc6, 0xf7, 0x23, 0x4d, 0x73, 0xac, 0x51, 0x36, 0x89, 0xa3, 0xe0, 0xc1, 0x79, 0xa7,
	0xea, 0x7f, 0x33, 0x27, 0xfc, 0x85, 0xea, 0xcd, 0xd7, 0x76, 0xf2, 0xe1, 0x79, 0xb6, 0x3a, 0x20,
	0xd7, 0xa3, 0xce, 0xc4, 0x9b, 0xfe, 0xf2, 0x80, 0x44, 0x8c, 0x66, 0x5c, 0x28, 0xac, 0x5d, 0xcc,
	0x5d, 0x23, 0x73, 0x6c, 0xbd, 0xbe, 0xc6, 0x15, 0x5e, 0x83, 0x5f, 0x99, 0xa0, 0xd2, 0x17, 0x91,
	0x13, 0x2f, 0xbd, 0x67, 0x9f, 0x3d, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x99, 0x70, 0x0b, 0x71,
	0xf1, 0x03, 0x00, 0x00,
}
