// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/api/networkdb/rpcif.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	components/api/networkdb/rpcif.proto

It has these top-level messages:
	Result
	Configuration
	JoinClusterReq
	GroupID
	Entry
	PeerList
	Peer
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperationResult int32

const (
	OperationResult_SUCCESS OperationResult = 0
	OperationResult_FAIL    OperationResult = 1
)

var OperationResult_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}
var OperationResult_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x OperationResult) String() string {
	return proto.EnumName(OperationResult_name, int32(x))
}
func (OperationResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Result struct {
	Status OperationResult `protobuf:"varint,1,opt,name=status,enum=api.OperationResult" json:"status,omitempty"`
	Error  string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Data   []byte          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetStatus() OperationResult {
	if m != nil {
		return m.Status
	}
	return OperationResult_SUCCESS
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Result) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Configuration struct {
	// NodeName is the cluster wide unique name for this node.
	NodeName string `protobuf:"bytes,1,opt,name=NodeName" json:"NodeName,omitempty"`
	// BindAddr is the IP on which networkdb listens.
	BindAddr string `protobuf:"bytes,2,opt,name=BindAddr" json:"BindAddr,omitempty"`
	// BindPort is the local node's port to which we bind to for cluster communication.
	BindPort int32 `protobuf:"varint,3,opt,name=BindPort" json:"BindPort,omitempty"`
	// Keys to be added to the Keyring of the memberlist. Key at index
	// 0 is the primary key
	Keys [][]byte `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Configuration) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *Configuration) GetBindAddr() string {
	if m != nil {
		return m.BindAddr
	}
	return ""
}

func (m *Configuration) GetBindPort() int32 {
	if m != nil {
		return m.BindPort
	}
	return 0
}

func (m *Configuration) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type JoinClusterReq struct {
	Members []string `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
}

func (m *JoinClusterReq) Reset()                    { *m = JoinClusterReq{} }
func (m *JoinClusterReq) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterReq) ProtoMessage()               {}
func (*JoinClusterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinClusterReq) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupID struct {
	GroupName string `protobuf:"bytes,1,opt,name=GroupName" json:"GroupName,omitempty"`
}

func (m *GroupID) Reset()                    { *m = GroupID{} }
func (m *GroupID) String() string            { return proto.CompactTextString(m) }
func (*GroupID) ProtoMessage()               {}
func (*GroupID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GroupID) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type Entry struct {
	Group     *GroupID `protobuf:"bytes,1,opt,name=Group" json:"Group,omitempty"`
	TableName string   `protobuf:"bytes,2,opt,name=TableName" json:"TableName,omitempty"`
	EntryName string   `protobuf:"bytes,3,opt,name=EntryName" json:"EntryName,omitempty"`
	Value     []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Entry) GetGroup() *GroupID {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *Entry) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *Entry) GetEntryName() string {
	if m != nil {
		return m.EntryName
	}
	return ""
}

func (m *Entry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PeerList struct {
	Peers []*Peer `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *PeerList) Reset()                    { *m = PeerList{} }
func (m *PeerList) String() string            { return proto.CompactTextString(m) }
func (*PeerList) ProtoMessage()               {}
func (*PeerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PeerList) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Peer struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "api.Result")
	proto.RegisterType((*Configuration)(nil), "api.Configuration")
	proto.RegisterType((*JoinClusterReq)(nil), "api.JoinClusterReq")
	proto.RegisterType((*GroupID)(nil), "api.GroupID")
	proto.RegisterType((*Entry)(nil), "api.Entry")
	proto.RegisterType((*PeerList)(nil), "api.PeerList")
	proto.RegisterType((*Peer)(nil), "api.Peer")
	proto.RegisterEnum("api.OperationResult", OperationResult_name, OperationResult_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConfigurationManagement service

type ConfigurationManagementClient interface {
	// Component initialization
	Initialize(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*Result, error)
}

type configurationManagementClient struct {
	cc *grpc.ClientConn
}

func NewConfigurationManagementClient(cc *grpc.ClientConn) ConfigurationManagementClient {
	return &configurationManagementClient{cc}
}

func (c *configurationManagementClient) Initialize(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.ConfigurationManagement/Initialize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConfigurationManagement service

type ConfigurationManagementServer interface {
	// Component initialization
	Initialize(context.Context, *Configuration) (*Result, error)
}

func RegisterConfigurationManagementServer(s *grpc.Server, srv ConfigurationManagementServer) {
	s.RegisterService(&_ConfigurationManagement_serviceDesc, srv)
}

func _ConfigurationManagement_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Configuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationManagementServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ConfigurationManagement/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationManagementServer).Initialize(ctx, req.(*Configuration))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfigurationManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ConfigurationManagement",
	HandlerType: (*ConfigurationManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _ConfigurationManagement_Initialize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/api/networkdb/rpcif.proto",
}

// Client API for ClusterManagement service

type ClusterManagementClient interface {
	// // Cluster related operations
	// rpc StateCluster () returns (State) {}
	JoinCluster(ctx context.Context, in *JoinClusterReq, opts ...grpc.CallOption) (*Result, error)
	// rpc LeaveCluster () returns (Result) {}
	PeersCluster(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PeerList, error)
}

type clusterManagementClient struct {
	cc *grpc.ClientConn
}

func NewClusterManagementClient(cc *grpc.ClientConn) ClusterManagementClient {
	return &clusterManagementClient{cc}
}

func (c *clusterManagementClient) JoinCluster(ctx context.Context, in *JoinClusterReq, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.ClusterManagement/JoinCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterManagementClient) PeersCluster(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*PeerList, error) {
	out := new(PeerList)
	err := grpc.Invoke(ctx, "/api.ClusterManagement/PeersCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClusterManagement service

type ClusterManagementServer interface {
	// // Cluster related operations
	// rpc StateCluster () returns (State) {}
	JoinCluster(context.Context, *JoinClusterReq) (*Result, error)
	// rpc LeaveCluster () returns (Result) {}
	PeersCluster(context.Context, *google_protobuf.Empty) (*PeerList, error)
}

func RegisterClusterManagementServer(s *grpc.Server, srv ClusterManagementServer) {
	s.RegisterService(&_ClusterManagement_serviceDesc, srv)
}

func _ClusterManagement_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ClusterManagement/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).JoinCluster(ctx, req.(*JoinClusterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterManagement_PeersCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterManagementServer).PeersCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ClusterManagement/PeersCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterManagementServer).PeersCluster(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ClusterManagement",
	HandlerType: (*ClusterManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinCluster",
			Handler:    _ClusterManagement_JoinCluster_Handler,
		},
		{
			MethodName: "PeersCluster",
			Handler:    _ClusterManagement_PeersCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/api/networkdb/rpcif.proto",
}

// Client API for GroupManagement service

type GroupManagementClient interface {
	// // Group operations
	JoinGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error)
	LeaveGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error)
	// rpc ListGroup () return (Result) {}
	PeersGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*PeerList, error)
}

type groupManagementClient struct {
	cc *grpc.ClientConn
}

func NewGroupManagementClient(cc *grpc.ClientConn) GroupManagementClient {
	return &groupManagementClient{cc}
}

func (c *groupManagementClient) JoinGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.GroupManagement/JoinGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagementClient) LeaveGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.GroupManagement/LeaveGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupManagementClient) PeersGroup(ctx context.Context, in *GroupID, opts ...grpc.CallOption) (*PeerList, error) {
	out := new(PeerList)
	err := grpc.Invoke(ctx, "/api.GroupManagement/PeersGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GroupManagement service

type GroupManagementServer interface {
	// // Group operations
	JoinGroup(context.Context, *GroupID) (*Result, error)
	LeaveGroup(context.Context, *GroupID) (*Result, error)
	// rpc ListGroup () return (Result) {}
	PeersGroup(context.Context, *GroupID) (*PeerList, error)
}

func RegisterGroupManagementServer(s *grpc.Server, srv GroupManagementServer) {
	s.RegisterService(&_GroupManagement_serviceDesc, srv)
}

func _GroupManagement_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupManagement/JoinGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).JoinGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManagement_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupManagement/LeaveGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).LeaveGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupManagement_PeersGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupManagementServer).PeersGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupManagement/PeersGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupManagementServer).PeersGroup(ctx, req.(*GroupID))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GroupManagement",
	HandlerType: (*GroupManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinGroup",
			Handler:    _GroupManagement_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _GroupManagement_LeaveGroup_Handler,
		},
		{
			MethodName: "PeersGroup",
			Handler:    _GroupManagement_PeersGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/api/networkdb/rpcif.proto",
}

// Client API for EntryManagement service

type EntryManagementClient interface {
	// // Entry operations
	CreateEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error)
	ReadEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error)
	UpdateEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error)
	DeleteEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error)
}

type entryManagementClient struct {
	cc *grpc.ClientConn
}

func NewEntryManagementClient(cc *grpc.ClientConn) EntryManagementClient {
	return &entryManagementClient{cc}
}

func (c *entryManagementClient) CreateEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.EntryManagement/CreateEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) ReadEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.EntryManagement/ReadEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) UpdateEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.EntryManagement/UpdateEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryManagementClient) DeleteEntryRpc(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.EntryManagement/DeleteEntryRpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EntryManagement service

type EntryManagementServer interface {
	// // Entry operations
	CreateEntryRpc(context.Context, *Entry) (*Result, error)
	ReadEntryRpc(context.Context, *Entry) (*Result, error)
	UpdateEntryRpc(context.Context, *Entry) (*Result, error)
	DeleteEntryRpc(context.Context, *Entry) (*Result, error)
}

func RegisterEntryManagementServer(s *grpc.Server, srv EntryManagementServer) {
	s.RegisterService(&_EntryManagement_serviceDesc, srv)
}

func _EntryManagement_CreateEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).CreateEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntryManagement/CreateEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).CreateEntryRpc(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_ReadEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).ReadEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntryManagement/ReadEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).ReadEntryRpc(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_UpdateEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).UpdateEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntryManagement/UpdateEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).UpdateEntryRpc(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryManagement_DeleteEntryRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryManagementServer).DeleteEntryRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntryManagement/DeleteEntryRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryManagementServer).DeleteEntryRpc(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntryManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EntryManagement",
	HandlerType: (*EntryManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntryRpc",
			Handler:    _EntryManagement_CreateEntryRpc_Handler,
		},
		{
			MethodName: "ReadEntryRpc",
			Handler:    _EntryManagement_ReadEntryRpc_Handler,
		},
		{
			MethodName: "UpdateEntryRpc",
			Handler:    _EntryManagement_UpdateEntryRpc_Handler,
		},
		{
			MethodName: "DeleteEntryRpc",
			Handler:    _EntryManagement_DeleteEntryRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/api/networkdb/rpcif.proto",
}

// Client API for DiagnoseManagement service

type DiagnoseManagementClient interface {
	Ready(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Result, error)
}

type diagnoseManagementClient struct {
	cc *grpc.ClientConn
}

func NewDiagnoseManagementClient(cc *grpc.ClientConn) DiagnoseManagementClient {
	return &diagnoseManagementClient{cc}
}

func (c *diagnoseManagementClient) Ready(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.DiagnoseManagement/Ready", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiagnoseManagement service

type DiagnoseManagementServer interface {
	Ready(context.Context, *google_protobuf.Empty) (*Result, error)
}

func RegisterDiagnoseManagementServer(s *grpc.Server, srv DiagnoseManagementServer) {
	s.RegisterService(&_DiagnoseManagement_serviceDesc, srv)
}

func _DiagnoseManagement_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnoseManagementServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DiagnoseManagement/Ready",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnoseManagementServer).Ready(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiagnoseManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DiagnoseManagement",
	HandlerType: (*DiagnoseManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ready",
			Handler:    _DiagnoseManagement_Ready_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/api/networkdb/rpcif.proto",
}

func init() { proto.RegisterFile("components/api/networkdb/rpcif.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x61, 0x4f, 0x13, 0x4d,
	0x10, 0xe6, 0x68, 0x0b, 0x74, 0x5a, 0x0a, 0xef, 0xbe, 0x44, 0x9b, 0x6a, 0x62, 0x73, 0x31, 0xb1,
	0x52, 0x73, 0x8d, 0xe7, 0x07, 0x3f, 0x63, 0x8b, 0x06, 0x02, 0x48, 0x16, 0xf1, 0xb3, 0x5b, 0x6e,
	0x68, 0x36, 0x5c, 0x77, 0xd7, 0xbd, 0x3d, 0x49, 0x4d, 0x8c, 0x3f, 0xc2, 0x9f, 0xe4, 0x1f, 0x33,
	0xbb, 0xdb, 0x2b, 0x57, 0xd0, 0xa4, 0xdf, 0x76, 0x66, 0x9e, 0x7d, 0xe6, 0x99, 0x79, 0x06, 0x9e,
	0x5f, 0xc9, 0xa9, 0x92, 0x02, 0x85, 0xc9, 0x06, 0x4c, 0xf1, 0x81, 0x40, 0x73, 0x2b, 0xf5, 0x4d,
	0x32, 0x1e, 0x68, 0x75, 0xc5, 0xaf, 0x23, 0xa5, 0xa5, 0x91, 0xa4, 0xc2, 0x14, 0xef, 0x3c, 0x99,
	0x48, 0x39, 0x49, 0x71, 0xe0, 0x52, 0xe3, 0xfc, 0x7a, 0x80, 0x53, 0x65, 0x66, 0x1e, 0x11, 0x7e,
	0x81, 0x0d, 0x8a, 0x59, 0x9e, 0x1a, 0xf2, 0x0a, 0x36, 0x32, 0xc3, 0x4c, 0x9e, 0xb5, 0x83, 0x6e,
	0xd0, 0x6b, 0xc5, 0x7b, 0x11, 0x53, 0x3c, 0xfa, 0xa8, 0x50, 0x33, 0xc3, 0xa5, 0xf0, 0x28, 0x3a,
	0xc7, 0x90, 0x3d, 0xa8, 0xa1, 0xd6, 0x52, 0xb7, 0xd7, 0xbb, 0x41, 0xaf, 0x4e, 0x7d, 0x40, 0x08,
	0x54, 0x13, 0x66, 0x58, 0xbb, 0xd2, 0x0d, 0x7a, 0x4d, 0xea, 0xde, 0xe1, 0x2d, 0x6c, 0x0f, 0xa5,
	0xb8, 0xe6, 0x93, 0xdc, 0x13, 0x91, 0x0e, 0x6c, 0x9d, 0xc9, 0x04, 0xcf, 0xd8, 0x14, 0x5d, 0xab,
	0x3a, 0x5d, 0xc4, 0xb6, 0xf6, 0x8e, 0x8b, 0xe4, 0x20, 0x49, 0x0a, 0xe6, 0x45, 0x5c, 0xd4, 0xce,
	0xa5, 0x36, 0xae, 0x41, 0x8d, 0x2e, 0x62, 0xdb, 0xf8, 0x06, 0x67, 0x59, 0xbb, 0xda, 0xad, 0xd8,
	0xc6, 0xf6, 0x1d, 0xee, 0x43, 0xeb, 0x58, 0x72, 0x31, 0x4c, 0xf3, 0xcc, 0xa0, 0xa6, 0xf8, 0x95,
	0xb4, 0x61, 0xf3, 0x14, 0xa7, 0x63, 0xd4, 0x76, 0xc6, 0x4a, 0xaf, 0x4e, 0x8b, 0x30, 0x7c, 0x01,
	0x9b, 0x1f, 0xb4, 0xcc, 0xd5, 0xd1, 0x88, 0x3c, 0x85, 0xba, 0x7b, 0x96, 0xf4, 0xdd, 0x25, 0xc2,
	0x1f, 0x50, 0x3b, 0x14, 0x46, 0xcf, 0x48, 0x08, 0x35, 0x97, 0x75, 0x90, 0x46, 0xdc, 0x74, 0xdb,
	0x9a, 0x73, 0x50, 0x5f, 0xb2, 0x54, 0x9f, 0xd8, 0x38, 0xf5, 0xa3, 0xfa, 0x71, 0xee, 0x12, 0xb6,
	0xea, 0xa8, 0x5c, 0xb5, 0xe2, 0xab, 0x8b, 0x84, 0x5d, 0xf0, 0x67, 0x96, 0xe6, 0xd8, 0xae, 0xba,
	0x5d, 0xfa, 0x20, 0xec, 0xc3, 0xd6, 0x39, 0xa2, 0x3e, 0xe1, 0x99, 0x21, 0xcf, 0xa0, 0xa6, 0xb0,
	0x98, 0xa5, 0x11, 0xd7, 0x9d, 0x02, 0x5b, 0xa5, 0x3e, 0x1f, 0xee, 0x43, 0xd5, 0x86, 0x76, 0x39,
	0xe2, 0x6e, 0x18, 0xf7, 0x26, 0x2d, 0x58, 0xe7, 0x6a, 0xae, 0x69, 0x9d, 0xab, 0xfd, 0x1e, 0xec,
	0xdc, 0xb3, 0x9a, 0x34, 0x60, 0xf3, 0xe2, 0x72, 0x38, 0x3c, 0xbc, 0xb8, 0xd8, 0x5d, 0x23, 0x5b,
	0x50, 0x7d, 0x7f, 0x70, 0x74, 0xb2, 0x1b, 0xc4, 0xc7, 0xf0, 0x78, 0xc9, 0xcf, 0x53, 0x26, 0xd8,
	0x04, 0xa7, 0x28, 0x0c, 0x19, 0x00, 0x1c, 0x09, 0x6e, 0x38, 0x4b, 0xf9, 0x77, 0x24, 0xc4, 0x09,
	0x5a, 0xc2, 0x76, 0x1a, 0x2e, 0xe7, 0x1b, 0x84, 0x6b, 0xf1, 0x4f, 0xf8, 0x6f, 0x6e, 0x4f, 0x89,
	0xe5, 0x35, 0x34, 0x4a, 0xbe, 0x91, 0xff, 0xdd, 0x97, 0x65, 0x27, 0xef, 0xf1, 0x90, 0xb7, 0xd0,
	0xb4, 0x93, 0x66, 0xc5, 0x9f, 0x47, 0x91, 0xbf, 0xf9, 0xa8, 0xb8, 0xf9, 0xe8, 0xd0, 0xde, 0x7c,
	0x67, 0x7b, 0xb1, 0x23, 0xbb, 0xc1, 0x70, 0x2d, 0xfe, 0x15, 0xc0, 0x8e, 0xf3, 0xaa, 0xd4, 0xbf,
	0x07, 0x75, 0xdb, 0xcd, 0x5b, 0xb8, 0xe4, 0xeb, 0xfd, 0xb6, 0x2f, 0x01, 0x4e, 0x90, 0x7d, 0xc3,
	0x15, 0xa0, 0x7d, 0x00, 0xa7, 0xf0, 0x6f, 0xd0, 0x07, 0xaa, 0x7e, 0x07, 0xb0, 0xe3, 0x2e, 0xa1,
	0xa4, 0xaa, 0x0f, 0xad, 0xa1, 0x46, 0x66, 0xd0, 0x15, 0xa8, 0xba, 0x22, 0xe0, 0xbe, 0xb9, 0xf0,
	0xa1, 0xb0, 0x26, 0x45, 0x96, 0xac, 0x02, 0xed, 0x43, 0xeb, 0x52, 0x25, 0x2b, 0xf2, 0xf6, 0xa1,
	0x35, 0xc2, 0x14, 0x57, 0x02, 0xc7, 0x23, 0x20, 0x23, 0xce, 0x26, 0x42, 0x66, 0x58, 0x9a, 0x23,
	0x82, 0x9a, 0x95, 0x36, 0xfb, 0xa7, 0x47, 0xcb, 0x2c, 0xe3, 0x0d, 0x57, 0x7e, 0xf3, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x3d, 0x39, 0xa5, 0x45, 0xf1, 0x04, 0x00, 0x00,
}
